import * as THREE from "three";

/**
 * Generated by img2blockbench from its Minecraft cuboid scene spec.
 * Edit the JSON specification, not this generated file.
 */
export function createChineseDragonBossModel(): THREE.Group {
  const root = new THREE.Group();
  root.name = "chinese_dragon_boss";
  const materials = [
    new THREE.MeshBasicMaterial({ name: "jade_scales", color: "#355b48", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "jade_light", color: "#4f8065", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "deep_jade", color: "#20372f", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "gold_belly", color: "#b99750", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "vermilion_mane", color: "#9e392d", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "bone", color: "#d5c6a0", toneMapped: false }),
    new THREE.MeshBasicMaterial({ name: "eye_gold", color: "#dbc37e", toneMapped: false }),
  ];

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(8, 7, 6.5033),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_00";
    mesh.position.set(0, 0, 3.0017);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_00_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.0333218260791, 3.14159265359, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(8.5, 7.2, 6.5605),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_01";
    mesh.position.set(0, 0, 3.0303);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_01_pivot";
    pivot.position.set(0, 18.2, 22);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.0495202268668, 3.00904187822, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(9, 7.5, 6.586),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_02";
    mesh.position.set(0, 0, 3.043);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_02_pivot";
    pivot.position.set(0.8, 18.5, 16);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.0328680404736, 2.97644436378, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(9.2, 7.6, 6.5539),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_03";
    mesh.position.set(0, 0, 3.027);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_03_pivot";
    pivot.position.set(1.8, 18.7, 10);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0661217987118, 3.02545146385, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(9, 7.5, 6.5283),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_04";
    mesh.position.set(0, 0, 3.0141);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_04_pivot";
    pivot.position.set(2.5, 18.3, 4);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0830375298221, -3.09163434908, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(8.8, 7.3, 6.5737),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_05";
    mesh.position.set(0, 0, 3.0369);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_05_pivot";
    pivot.position.set(2.2, 17.8, -2);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0824144472792, -3.00904187822, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(8.5, 7, 6.6262),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_06";
    mesh.position.set(0, 0, 3.0631);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_06_pivot";
    pivot.position.set(1.4, 17.3, -8);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0489896467742, -2.94419766052, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(8.2, 6.8, 6.6221),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_07";
    mesh.position.set(0, 0, 3.061);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_07_pivot";
    pivot.position.set(0.2, 17, -14);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.0326743089266, -2.94419766052, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(7.8, 6.4, 6.5737),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_08";
    mesh.position.set(0, 0, 3.0369);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_08_pivot";
    pivot.position.set(-1, 17.2, -20);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.0824144472792, -3.00904187822, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(7.3, 6, 6.5241),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_09";
    mesh.position.set(0, 0, 3.0121);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_09_pivot";
    pivot.position.set(-1.8, 17.7, -26);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.0830951256875, -3.10827082751, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(6.8, 5.6, 6.5208),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_10";
    mesh.position.set(0, 0, 3.0104);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_10_pivot";
    pivot.position.set(-2, 18.2, -32);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.0498483487662, 3.07502405059, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(6.2, 5.1, 6.5564),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_11";
    mesh.position.set(0, 0, 3.0282);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_11_pivot";
    pivot.position.set(-1.6, 18.5, -38);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0330286107647, 3.00904187822, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(5.5, 4.6, 6.5803),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_12";
    mesh.position.set(0, 0, 3.0401);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_12_pivot";
    pivot.position.set(-0.8, 18.3, -44);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0658338193852, 2.99270210576, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4.8, 4, 6.5737),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_13";
    mesh.position.set(0, 0, 3.0369);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_13_pivot";
    pivot.position.set(0.1, 17.9, -50);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0824144472792, 3.00904187822, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4, 3.4, 6.029),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_14";
    mesh.position.set(0, 0, 2.7645);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_14_pivot";
    pivot.position.set(0.9, 17.4, -56);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0724084746775, 3.06899393802, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3.2, 2.8, 5.513),
      [materials[0], materials[0], materials[0], materials[3], materials[0], materials[0]],
    );
    mesh.name = "body_segment_15";
    mesh.position.set(0, 0, 2.5065);
    const pivot = new THREE.Group();
    pivot.name = "body_segment_15_pivot";
    pivot.position.set(1.3, 17, -61.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.0598805013067, 3.10161414174, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(10, 8.5, 10),
      [materials[0], materials[0], materials[0], materials[0], materials[0], materials[0]],
    );
    mesh.name = "cranium";
    mesh.position.set(0, 2.2, 5);
    const pivot = new THREE.Group();
    pivot.name = "cranium_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(8, 5, 7.5),
      [materials[1], materials[1], materials[1], materials[1], materials[1], materials[1]],
    );
    mesh.name = "upper_snout";
    mesh.position.set(0, 0.2, 12.5);
    const pivot = new THREE.Group();
    pivot.name = "upper_snout_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(8, 2.5, 7.5),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "lower_jaw";
    mesh.position.set(0, -0.7, 2.2);
    const pivot = new THREE.Group();
    pivot.name = "lower_jaw_pivot";
    pivot.position.set(0, 16, 38);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 3.2, 3),
      [materials[6], materials[6], materials[6], materials[6], materials[6], materials[6]],
    );
    mesh.name = "eye_left";
    mesh.position.set(4.7, 3.8, 7.2);
    const pivot = new THREE.Group();
    pivot.name = "eye_left_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 3.2, 3),
      [materials[6], materials[6], materials[6], materials[6], materials[6], materials[6]],
    );
    mesh.name = "eye_right";
    mesh.position.set(-4.7, 3.8, 7.2);
    const pivot = new THREE.Group();
    pivot.name = "eye_right_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.2, 2, 5.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "brow_left";
    mesh.position.set(4.4, 5.7, 7);
    const pivot = new THREE.Group();
    pivot.name = "brow_left_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.2, 2, 5.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "brow_right";
    mesh.position.set(-4.4, 5.7, 7);
    const pivot = new THREE.Group();
    pivot.name = "brow_right_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2, 4.5, 3),
      [materials[2], materials[2], materials[2], materials[2], materials[2], materials[2]],
    );
    mesh.name = "ear_left";
    mesh.position.set(5.5, 3.4, 1.7);
    const pivot = new THREE.Group();
    pivot.name = "ear_left_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2, 4.5, 3),
      [materials[2], materials[2], materials[2], materials[2], materials[2], materials[2]],
    );
    mesh.name = "ear_right";
    mesh.position.set(-5.5, 3.4, 1.7);
    const pivot = new THREE.Group();
    pivot.name = "ear_right_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3.5, 4, 5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "chin_beard";
    mesh.position.set(0, -3.2, -1.2);
    const pivot = new THREE.Group();
    pivot.name = "chin_beard_pivot";
    pivot.position.set(0, 16, 38);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4.5, 3.5, 5),
      [materials[1], materials[1], materials[1], materials[1], materials[1], materials[1]],
    );
    mesh.name = "nose_bridge";
    mesh.position.set(0, 2, 10.5);
    const pivot = new THREE.Group();
    pivot.name = "nose_bridge_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(7, 4, 2.5),
      [materials[2], materials[2], materials[2], materials[2], materials[2], materials[2]],
    );
    mesh.name = "nose_pad";
    mesh.position.set(0, 0.6, 16.4);
    const pivot = new THREE.Group();
    pivot.name = "nose_pad_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.8, 5.5, 3.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_crown_left";
    mesh.position.set(3.4, 8.2, 4.5);
    const pivot = new THREE.Group();
    pivot.name = "mane_crown_left_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.436332312999);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.8, 5.5, 3.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_crown_right";
    mesh.position.set(-3.4, 8.2, 4.5);
    const pivot = new THREE.Group();
    pivot.name = "mane_crown_right_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.436332312999);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 5, 3.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_cheek_left";
    mesh.position.set(6.7, 2.2, 4);
    const pivot = new THREE.Group();
    pivot.name = "mane_cheek_left_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.610865238198);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 5, 3.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_cheek_right";
    mesh.position.set(-6.7, 2.2, 4);
    const pivot = new THREE.Group();
    pivot.name = "mane_cheek_right_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.610865238198);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 4.5, 3.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_jowl_left";
    mesh.position.set(5.4, -2.3, 5);
    const pivot = new THREE.Group();
    pivot.name = "mane_jowl_left_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.610865238198);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 4.5, 3.5),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_jowl_right";
    mesh.position.set(-5.4, -2.3, 5);
    const pivot = new THREE.Group();
    pivot.name = "mane_jowl_right_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.610865238198);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 5.5, 4),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_neck_left";
    mesh.position.set(5, 2.8, -0.5);
    const pivot = new THREE.Group();
    pivot.name = "mane_neck_left_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.261799387799, 0, -0.436332312999);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 5.5, 4),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_neck_right";
    mesh.position.set(-5, 2.8, -0.5);
    const pivot = new THREE.Group();
    pivot.name = "mane_neck_right_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.261799387799, 0, 0.436332312999);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 5, 4),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_neck_top";
    mesh.position.set(0, 6, -1);
    const pivot = new THREE.Group();
    pivot.name = "mane_neck_top_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.349065850399, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3, 5, 4),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "mane_throat";
    mesh.position.set(0, -3.8, 0.2);
    const pivot = new THREE.Group();
    pivot.name = "mane_throat_pivot";
    pivot.position.set(0, 18, 28);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.349065850399, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.5, 1.5, 5.9772),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_left_base";
    mesh.position.set(0, 0, 2.7386);
    const pivot = new THREE.Group();
    pivot.name = "horn_left_base_pivot";
    pivot.position.set(3, 24.5, 32);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-1.15026273419, 2.96173996483, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.3, 1.3, 6.4741),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_left_shaft";
    mesh.position.set(0, 0, 2.9871);
    const pivot = new THREE.Group();
    pivot.name = "horn_left_shaft_pivot";
    pivot.position.set(3.4, 29.5, 29.8);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.905490778569, 2.92292384227, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1, 1, 6.1956),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_left_tip";
    mesh.position.set(0, 0, 2.8478);
    const pivot = new THREE.Group();
    pivot.name = "horn_left_tip_pivot";
    pivot.position.set(4.2, 34.2, 26.2);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.730416801301, 2.99969564007, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1, 1, 4.9385),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_left_front_branch";
    mesh.position.set(0, 0, 2.2192);
    const pivot = new THREE.Group();
    pivot.name = "horn_left_front_branch_pivot";
    pivot.position.set(3.5, 29.8, 29.4);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.653939964137, 1.68458830337, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.9, 0.9, 5.1054),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_left_rear_branch";
    mesh.position.set(0, 0, 2.3027);
    const pivot = new THREE.Group();
    pivot.name = "horn_left_rear_branch_pivot";
    pivot.position.set(4.1, 34, 26.4);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.498031447386, 2.26869938946, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.5, 1.5, 5.9772),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_right_base";
    mesh.position.set(0, 0, 2.7386);
    const pivot = new THREE.Group();
    pivot.name = "horn_right_base_pivot";
    pivot.position.set(-3, 24.5, 32);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-1.15026273419, -2.96173996483, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.3, 1.3, 6.4741),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_right_shaft";
    mesh.position.set(0, 0, 2.9871);
    const pivot = new THREE.Group();
    pivot.name = "horn_right_shaft_pivot";
    pivot.position.set(-3.4, 29.5, 29.8);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.905490778569, -2.92292384227, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1, 1, 6.1956),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_right_tip";
    mesh.position.set(0, 0, 2.8478);
    const pivot = new THREE.Group();
    pivot.name = "horn_right_tip_pivot";
    pivot.position.set(-4.2, 34.2, 26.2);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.730416801301, -2.99969564007, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1, 1, 4.9385),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_right_front_branch";
    mesh.position.set(0, 0, 2.2192);
    const pivot = new THREE.Group();
    pivot.name = "horn_right_front_branch_pivot";
    pivot.position.set(-3.5, 29.8, 29.4);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.653939964137, -1.68458830337, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.9, 0.9, 5.1054),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "horn_right_rear_branch";
    mesh.position.set(0, 0, 2.3027);
    const pivot = new THREE.Group();
    pivot.name = "horn_right_rear_branch_pivot";
    pivot.position.set(-4.1, 34, 26.4);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.498031447386, -2.26869938946, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 5.5488),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_left_segment_0";
    mesh.position.set(0, 0, 2.5244);
    const pivot = new THREE.Group();
    pivot.name = "whisker_left_segment_0_pivot";
    pivot.position.set(3.5, 17.2, 43);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.139095760067, 0.927295176914, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.8875),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_left_segment_1";
    mesh.position.set(0, 0, 2.1937);
    const pivot = new THREE.Group();
    pivot.name = "whisker_left_segment_1_pivot";
    pivot.position.set(7.5, 16.5, 46);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.348919242742, 1.32581842233, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.5927),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_left_segment_2";
    mesh.position.set(0, 0, 2.0463);
    const pivot = new THREE.Group();
    pivot.name = "whisker_left_segment_2_pivot";
    pivot.position.set(11.5, 15, 47);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.375252770496, 1.97568827865, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.5311),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_left_segment_3";
    mesh.position.set(0, 0, 2.0156);
    const pivot = new THREE.Group();
    pivot.name = "whisker_left_segment_3_pivot";
    pivot.position.set(15, 13.5, 45.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.250686876452, 2.44685387286, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.1401),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_left_segment_4";
    mesh.position.set(0, 0, 1.82);
    const pivot = new THREE.Group();
    pivot.name = "whisker_left_segment_4_pivot";
    pivot.position.set(17.5, 14.5, 42.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.581697295739, 2.97644436378, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 5.5488),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_right_segment_0";
    mesh.position.set(0, 0, 2.5244);
    const pivot = new THREE.Group();
    pivot.name = "whisker_right_segment_0_pivot";
    pivot.position.set(-3.5, 17.2, 43);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.139095760067, -0.927295176914, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.8875),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_right_segment_1";
    mesh.position.set(0, 0, 2.1937);
    const pivot = new THREE.Group();
    pivot.name = "whisker_right_segment_1_pivot";
    pivot.position.set(-7.5, 16.5, 46);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.348919242742, -1.32581842233, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.5927),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_right_segment_2";
    mesh.position.set(0, 0, 2.0463);
    const pivot = new THREE.Group();
    pivot.name = "whisker_right_segment_2_pivot";
    pivot.position.set(-11.5, 15, 47);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.375252770496, -1.97568827865, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.5311),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_right_segment_3";
    mesh.position.set(0, 0, 2.0156);
    const pivot = new THREE.Group();
    pivot.name = "whisker_right_segment_3_pivot";
    pivot.position.set(-15, 13.5, 45.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.250686876452, -2.44685387286, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.8, 0.8, 4.1401),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "whisker_right_segment_4";
    mesh.position.set(0, 0, 1.82);
    const pivot = new THREE.Group();
    pivot.name = "whisker_right_segment_4_pivot";
    pivot.position.set(-17.5, 14.5, 42.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.581697295739, -2.97644436378, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3.2, 3.2, 8.2801),
      [materials[0], materials[0], materials[0], materials[0], materials[0], materials[0]],
    );
    mesh.name = "front_left_upper_leg";
    mesh.position.set(0, 0, 3.8901);
    const pivot = new THREE.Group();
    pivot.name = "front_left_upper_leg_pivot";
    pivot.position.set(5.756, 18.2, 10);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.988976858009, 1.38257478427, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.5, 2.5, 7.1393),
      [materials[2], materials[2], materials[2], materials[2], materials[2], materials[2]],
    );
    mesh.name = "front_left_lower_leg";
    mesh.position.set(0, 0, 3.3196);
    const pivot = new THREE.Group();
    pivot.name = "front_left_lower_leg_pivot";
    pivot.position.set(9.956, 11.7, 10.8);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(1.12836408806, 0.685729391133, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4.8, 2.2, 4.6231),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "front_left_paw";
    mesh.position.set(0, 0, 2.0616);
    const pivot = new THREE.Group();
    pivot.name = "front_left_paw_pivot";
    pivot.position.set(11.756, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.244977904468, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "front_left_claw_0";
    mesh.position.set(-1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "front_left_claw_0_pivot";
    pivot.position.set(11.756, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, -0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5594),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "front_left_claw_1";
    mesh.position.set(0, -1.5, 6.7297);
    const pivot = new THREE.Group();
    pivot.name = "front_left_claw_1_pivot";
    pivot.position.set(11.756, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.197394993071, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "front_left_claw_2";
    mesh.position.set(1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "front_left_claw_2_pivot";
    pivot.position.set(11.756, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, 0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3.2, 3.2, 8.2801),
      [materials[0], materials[0], materials[0], materials[0], materials[0], materials[0]],
    );
    mesh.name = "front_right_upper_leg";
    mesh.position.set(0, 0, 3.8901);
    const pivot = new THREE.Group();
    pivot.name = "front_right_upper_leg_pivot";
    pivot.position.set(-2.156, 18.2, 10);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.988976858009, -1.38257478427, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.5, 2.5, 7.1393),
      [materials[2], materials[2], materials[2], materials[2], materials[2], materials[2]],
    );
    mesh.name = "front_right_lower_leg";
    mesh.position.set(0, 0, 3.3196);
    const pivot = new THREE.Group();
    pivot.name = "front_right_lower_leg_pivot";
    pivot.position.set(-6.356, 11.7, 10.8);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(1.12836408806, -0.685729391133, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4.8, 2.2, 4.6231),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "front_right_paw";
    mesh.position.set(0, 0, 2.0616);
    const pivot = new THREE.Group();
    pivot.name = "front_right_paw_pivot";
    pivot.position.set(-8.156, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.244977904468, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "front_right_claw_0";
    mesh.position.set(1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "front_right_claw_0_pivot";
    pivot.position.set(-8.156, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, 0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5594),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "front_right_claw_1";
    mesh.position.set(0, -1.5, 6.7297);
    const pivot = new THREE.Group();
    pivot.name = "front_right_claw_1_pivot";
    pivot.position.set(-8.156, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.197394993071, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "front_right_claw_2";
    mesh.position.set(-1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "front_right_claw_2_pivot";
    pivot.position.set(-8.156, 5.7, 13);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, -0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3.2, 3.2, 8.2801),
      [materials[0], materials[0], materials[0], materials[0], materials[0], materials[0]],
    );
    mesh.name = "rear_left_upper_leg";
    mesh.position.set(0, 0, 3.8901);
    const pivot = new THREE.Group();
    pivot.name = "rear_left_upper_leg_pivot";
    pivot.position.set(0.924, 17.7, -32);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.988976858009, 1.38257478427, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.5, 2.5, 7.1393),
      [materials[2], materials[2], materials[2], materials[2], materials[2], materials[2]],
    );
    mesh.name = "rear_left_lower_leg";
    mesh.position.set(0, 0, 3.3196);
    const pivot = new THREE.Group();
    pivot.name = "rear_left_lower_leg_pivot";
    pivot.position.set(5.124, 11.2, -31.2);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(1.12836408806, 0.685729391133, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4.8, 2.2, 4.6231),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "rear_left_paw";
    mesh.position.set(0, 0, 2.0616);
    const pivot = new THREE.Group();
    pivot.name = "rear_left_paw_pivot";
    pivot.position.set(6.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.244977904468, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "rear_left_claw_0";
    mesh.position.set(-1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "rear_left_claw_0_pivot";
    pivot.position.set(6.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, -0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5594),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "rear_left_claw_1";
    mesh.position.set(0, -1.5, 6.7297);
    const pivot = new THREE.Group();
    pivot.name = "rear_left_claw_1_pivot";
    pivot.position.set(6.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.197394993071, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "rear_left_claw_2";
    mesh.position.set(1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "rear_left_claw_2_pivot";
    pivot.position.set(6.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, 0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(3.2, 3.2, 8.2801),
      [materials[0], materials[0], materials[0], materials[0], materials[0], materials[0]],
    );
    mesh.name = "rear_right_upper_leg";
    mesh.position.set(0, 0, 3.8901);
    const pivot = new THREE.Group();
    pivot.name = "rear_right_upper_leg_pivot";
    pivot.position.set(-4.924, 17.7, -32);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.988976858009, -1.38257478427, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(2.5, 2.5, 7.1393),
      [materials[2], materials[2], materials[2], materials[2], materials[2], materials[2]],
    );
    mesh.name = "rear_right_lower_leg";
    mesh.position.set(0, 0, 3.3196);
    const pivot = new THREE.Group();
    pivot.name = "rear_right_lower_leg_pivot";
    pivot.position.set(-9.124, 11.2, -31.2);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(1.12836408806, -0.685729391133, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(4.8, 2.2, 4.6231),
      [materials[3], materials[3], materials[3], materials[3], materials[3], materials[3]],
    );
    mesh.name = "rear_right_paw";
    mesh.position.set(0, 0, 2.0616);
    const pivot = new THREE.Group();
    pivot.name = "rear_right_paw_pivot";
    pivot.position.set(-10.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.244977904468, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "rear_right_claw_0";
    mesh.position.set(1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "rear_right_claw_0_pivot";
    pivot.position.set(-10.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, 0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5594),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "rear_right_claw_1";
    mesh.position.set(0, -1.5, 6.7297);
    const pivot = new THREE.Group();
    pivot.name = "rear_right_claw_1_pivot";
    pivot.position.set(-10.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.197394993071, 0, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(0.7, 0.7, 3.5984),
      [materials[5], materials[5], materials[5], materials[5], materials[5], materials[5]],
    );
    mesh.name = "rear_right_claw_2";
    mesh.position.set(-1.4, -1.5, 6.7492);
    const pivot = new THREE.Group();
    pivot.name = "rear_right_claw_2_pivot";
    pivot.position.set(-10.924, 5.2, -29);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0.194879973619, -0.161903722732, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 4.5, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_00";
    mesh.position.set(0, 5.769, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_00_pivot";
    pivot.position.set(0, 18.2, 22);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 4.37, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_01";
    mesh.position.set(0, 5.8665, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_01_pivot";
    pivot.position.set(0.8, 18.5, 16);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 4.24, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_02";
    mesh.position.set(0, 5.86, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_02_pivot";
    pivot.position.set(1.8, 18.7, 10);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 4.11, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_03";
    mesh.position.set(0, 5.7495, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_03_pivot";
    pivot.position.set(2.5, 18.3, 4);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 3.98, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_04";
    mesh.position.set(0, 5.587, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_04_pivot";
    pivot.position.set(2.2, 17.8, -2);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 3.85, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_05";
    mesh.position.set(0, 5.3725, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_05_pivot";
    pivot.position.set(1.4, 17.3, -8);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 3.72, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_06";
    mesh.position.set(0, 5.21, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_06_pivot";
    pivot.position.set(0.2, 17, -14);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 3.59, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_07";
    mesh.position.set(0, 4.9435, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_07_pivot";
    pivot.position.set(-1, 17.2, -20);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 3.46, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_08";
    mesh.position.set(0, 4.677, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_08_pivot";
    pivot.position.set(-1.8, 17.7, -26);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 3.33, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_09";
    mesh.position.set(0, 4.4105, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_09_pivot";
    pivot.position.set(-2, 18.2, -32);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, -0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 3.2, 2.8),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "dorsal_spine_10";
    mesh.position.set(0, 4.092, 0);
    const pivot = new THREE.Group();
    pivot.name = "dorsal_spine_10_pivot";
    pivot.position.set(-1.6, 18.5, -38);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(0, 0, 0.13962634016);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 2.8, 7.2268),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "tail_flame_0";
    mesh.position.set(0, 0, 3.3634);
    const pivot = new THREE.Group();
    pivot.name = "tail_flame_0_pivot";
    pivot.position.set(1.5, 16.7, -66.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0.837981443102, 3.14159265359, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 2.8, 7.0795),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "tail_flame_1";
    mesh.position.set(0, 0, 3.2898);
    const pivot = new THREE.Group();
    pivot.name = "tail_flame_1_pivot";
    pivot.position.set(1.5, 16.7, -66.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0, 2.38844119345, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  {
    const mesh = new THREE.Mesh(
      new THREE.BoxGeometry(1.6, 2.8, 7.0795),
      [materials[4], materials[4], materials[4], materials[4], materials[4], materials[4]],
    );
    mesh.name = "tail_flame_2";
    mesh.position.set(0, 0, 3.2898);
    const pivot = new THREE.Group();
    pivot.name = "tail_flame_2_pivot";
    pivot.position.set(1.5, 16.7, -66.5);
    pivot.rotation.order = "ZYX";
    pivot.rotation.set(-0, -2.38844119345, 0);
    pivot.add(mesh);
    root.add(pivot);
  }

  root.userData.img2blockbench = {
    representation: "minecraft-cuboids",
    componentCount: 96,
    source: "agent-authored-image-reconstruction",
  };
  return root;
}
